name: does-it-build
on:
    push:
    pull_request:
        branches: main

jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
    - run: npm run build
