name: connect-to-db
on:
  push:
    branches: git-action-connect-to-db
  pull_request:
    branches: main

jobs:
  run-db-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install
      working-directory: backend

    - name: Run testDatabase.ts
      run: npx ts-node tests/testDatabase.ts
      working-directory: backend