# This workflow will deploy the application to the running environment after a successful merge to main

name: deploy

on:
  push:
    branches:
      - main

jobs:
    on-success:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js environment
              uses: actions/setup-node@v2
              with:
                node-version: '21.3.0' # specify the Node.js version to use
                cache: 'npm' # cache the npm dependencies

            - name: Install dependencies
              working-directory: MuscleMate
              run: |
                npm ci
                

            - name: Build TypeScript
              working-directory: MuscleMate
              run: |
                npm run build

            - name: Zip the application
              run: |
                Compress-Archive -Path ./* -DestinationPath "MuscleMate_deploy-${{github.sha}}.zip"

            - name: Upload application artifact
              uses: actions/upload-artifact@v3
              with:
                name: MuscleMate_application_artifact
                path: MuscleMate_deploy-${{github.sha}}.zip

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                aws-region: "us-east-1" 

            - name: Upload application file to AWS
              run: aws s3 cp MuscleMate_deploy-${{github.sha}}.zip s3://cancanneed23-musclemate

            - name: Create new application version
              run: |  
                aws elasticbeanstalk create-application-version \
                --application-name MuscleMate \ 
                --source-bundle S3Bucket="cancanneed23-musclemate",S3Key="MuscleMate_deploy-${{github.sha}}.zip " \
                --version-label "ver-${{ github.sha }}" \
                --description "commit-sha-${{ github.sha }}"

            - name: Deploy application
              run: aws elasticbeanstalk update-environment --environment-name flaskbb-environment --version-label "ver-${{ github.sha }}"