name: running backend tests

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: install all backend dependencies
        run: cd backend && npm install
      
      - name: testing
        run: ls

      - name: Run Jest tests
        run: cd backend && npm test